spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/ccommerce
    username: sa
    password:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.sql: debug
    root: info
server:
  port: 8080
jwt:
  secret: ${secret}
  expiration_time: ${expiration_time}
  refresh_expiration_time: ${refresh_expiration_time}