spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/ccommerce
    username: sa
    password:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2000
          starttls:
            enable: true
logging:
  level:
    org.hibernate.sql: debug
    root: info
server:
  port: 8080
jwt:
  secret: ${secret}
  expiration_time: ${expiration_time}
  refresh_expiration_time: ${refresh_expiration_time}

default:
  protocol: http
  host: localhost
  port: 8080